### PR TITLE
Open source and support Python 3

### PR DESCRIPTION
**Pull request by ludwigschwardt**
This releases the code under the BSD 3-Clause license, as
[authorised](https://github.com/ska-sa/katversion/files/361159/RF2016-017-019_SKA_RSP_13.June.2016.1.pdf) by NIPMO.

In the process I also added support for Python 3 and now
build universal wheels by default.

The next steps after this PR are:

  - Fix pip sdist installs in a separate pull request
  - Tag the repository as v0.6
  - Upload the package to PyPI

That should simplify the installation of all other KAT packages that depend
on it :-)

I named the copyright holder **"National Research Foundation (Square Kilometre Array)"** as that was the wording in the NIPMO document. Any comments on this welcome.

### CODE REVIEW

**Comment by lvdheever** [comment]
Looks OK to me. If TA is happy he can merge.

**Comment by ludwigschwardt** [comment]
Just fixing a potential bug... Give me 5 minutes :-)

**Comment by ludwigschwardt** [comment]
OK, false alarm, go ahead...

**Comment by theunsa** [comment]
Netjies.

**Pull request merged**
